//! Emit `config.h` patches from `[config]` section of `features.toml`.

use std::fmt::Write;

use anyhow::Result;

use crate::schema::features::FeaturesToml;

/// QMK macros that are *boolean toggles*: `#define` enables the feature,
/// any other form (`#define X false`, `#undef X`) disables it. For these
/// macros we emit the `#define` only when the user wrote `true`.
const QMK_DEFINE_ONLY_BOOLEANS: &[&str] = &[
    "PERMISSIVE_HOLD",
    "HOLD_ON_OTHER_KEY_PRESS",
    "RETRO_TAPPING",
    "IGNORE_MOD_TAP_INTERRUPT",
    "TAPPING_FORCE_HOLD",
    "TAPPING_TERM_PER_KEY",
    "QUICK_TAP_TERM_PER_KEY",
    "PERMISSIVE_HOLD_PER_KEY",
    "HOLD_ON_OTHER_KEY_PRESS_PER_KEY",
    "CHORDAL_HOLD",
    "CAPS_WORD_INVERT_ON_SHIFT",
    "FORCE_NKRO",
    "MOUSEKEY_INERTIA",
];

/// Emit the additive `config.h` body. The QMK keymap include order is
/// `<keymap>/config.h` last, so anything we `#define` here overrides
/// upstream defaults. We `#undef` first when overriding (for macros
/// with values) to avoid `-Wmacro-redefined` warnings.
///
/// Returns an error if any known-typed config key is malformed (e.g.
/// `tapping_term_ms = -5`). Letting a bad value through would produce
/// a config.h that fails to compile deep inside QMK with a confusing
/// message — surfacing it at generation time gives the user a line
/// number in their features.toml.
pub fn emit_config_h(features: &FeaturesToml) -> Result<String> {
    // Validate known-typed keys up front so a bad value fails at
    // generation time rather than at QMK compile time.
    features.tapping_term_ms()?;

    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: MIT\n");
    out.push_str("// Generated by oryx-bench. Do not edit by hand.\n");
    out.push_str("#pragma once\n\n");

    let mut keys: Vec<&String> = features.config.keys().collect();
    keys.sort();
    for key in keys {
        let value = &features.config[key];
        let macro_name = key.to_uppercase();

        // Special-case define-only boolean toggles: skip when false,
        // emit a bare #define when true.
        if let toml::Value::Boolean(b) = value {
            if QMK_DEFINE_ONLY_BOOLEANS.contains(&macro_name.as_str()) {
                if *b {
                    let _ = writeln!(out, "#define {macro_name}");
                }
                // false → emit nothing (the QMK default is "not defined").
                continue;
            }
        }

        let _ = writeln!(out, "#undef {macro_name}");
        let _ = writeln!(out, "#define {macro_name} {}", render_toml_value(value));
    }

    Ok(out)
}

fn render_toml_value(v: &toml::Value) -> String {
    match v {
        // Strings are wrapped in `"..."` and the contents are escaped
        // using the same rules as `escape_c_string` in features.rs.
        // Without escaping, a user-supplied `[config]` value
        // containing a `"` or `\` would produce malformed `#define`
        // (or worse, inject arbitrary preprocessor tokens). Routing
        // through the same helper keeps the escape rules in one place.
        toml::Value::String(s) => format!("\"{}\"", escape_c_config_string(s)),
        toml::Value::Integer(i) => i.to_string(),
        toml::Value::Float(f) => f.to_string(),
        toml::Value::Boolean(true) => "true".to_string(),
        toml::Value::Boolean(false) => "false".to_string(),
        toml::Value::Array(_) | toml::Value::Table(_) | toml::Value::Datetime(_) => {
            // Architecture doesn't allow nested config — fall back to TOML repr.
            v.to_string()
        }
    }
}

/// Escape a string for embedding in a `#define FOO "..."` line of a
/// generated `config.h`. Same rules as the SEND_STRING escaper in
/// `features.rs::escape_c_string` (it's the same target language) but
/// inlined here to avoid a cross-module dependency that would
/// otherwise be the only reason features.rs is pub.
fn escape_c_config_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            // ASCII control chars: emit `\xNN""` (the trailing empty
            // string terminates C's greedy hex-digit run; see the
            // doc on `escape_c_string` in features.rs for the why).
            c if (c as u32) < 0x20 || (c as u32) == 0x7F => {
                use std::fmt::Write as _;
                let _ = write!(out, "\\x{:02X}\"\"", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn emits_pragma_once_and_undef_define_pairs() {
        // Use only non-boolean QMK macros here; boolean toggles get
        // their own dedicated tests below since the rendering rule is
        // different.
        let mut config = BTreeMap::new();
        config.insert("tapping_term_ms".to_string(), toml::Value::Integer(220));
        config.insert(
            "caps_word_idle_timeout_ms".to_string(),
            toml::Value::Integer(5000),
        );
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        assert!(out.contains("#pragma once"));
        assert!(out.contains("#undef TAPPING_TERM_MS"));
        assert!(out.contains("#define TAPPING_TERM_MS 220"));
        assert!(out.contains("#undef CAPS_WORD_IDLE_TIMEOUT_MS"));
        assert!(out.contains("#define CAPS_WORD_IDLE_TIMEOUT_MS 5000"));
    }

    #[test]
    fn empty_features_still_emits_header() {
        let out = emit_config_h(&FeaturesToml::default()).unwrap();
        assert!(out.contains("#pragma once"));
    }

    #[test]
    fn permissive_hold_true_emits_bare_define() {
        let mut config = BTreeMap::new();
        config.insert("permissive_hold".into(), toml::Value::Boolean(true));
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        assert!(out.contains("#define PERMISSIVE_HOLD\n"));
        assert!(!out.contains("#define PERMISSIVE_HOLD true"));
        assert!(!out.contains("#undef PERMISSIVE_HOLD"));
    }

    #[test]
    fn permissive_hold_false_emits_nothing() {
        let mut config = BTreeMap::new();
        config.insert("permissive_hold".into(), toml::Value::Boolean(false));
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        assert!(!out.contains("PERMISSIVE_HOLD"));
    }

    #[test]
    fn non_boolean_qmk_macro_still_uses_undef_define_pair() {
        let mut config = BTreeMap::new();
        config.insert("tapping_term_ms".into(), toml::Value::Integer(220));
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        assert!(out.contains("#undef TAPPING_TERM_MS"));
        assert!(out.contains("#define TAPPING_TERM_MS 220"));
    }

    #[test]
    fn emit_config_h_escapes_quotes_in_string_values() {
        // Regression: a user-supplied string containing `"` or `\`
        // would previously produce malformed `#define` lines (or
        // worse, inject arbitrary preprocessor tokens).
        let mut config = BTreeMap::new();
        config.insert(
            "manufacturer".into(),
            toml::Value::String(r#"My "Cool" Co\Brand"#.to_string()),
        );
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        // The output should contain a properly escaped #define
        // — not a stray unescaped `"` or `\`.
        assert!(
            out.contains(r#"#define MANUFACTURER "My \"Cool\" Co\\Brand""#),
            "expected escaped #define, got:\n{out}"
        );
    }

    #[test]
    fn emit_config_h_escapes_control_chars_in_string_values() {
        // Same `\xNN""` boundary discipline as escape_c_string in
        // features.rs — a control char followed by a hex letter
        // must not get absorbed into the escape.
        let mut config = BTreeMap::new();
        config.insert(
            "weird".into(),
            toml::Value::String("\x07A".to_string()), // BEL + 'A'
        );
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let out = emit_config_h(&features).unwrap();
        assert!(
            out.contains(r#"#define WEIRD "\x07""A""#),
            "expected hex escape with empty-string terminator, got:\n{out}"
        );
    }

    #[test]
    fn emit_config_h_rejects_negative_tapping_term() {
        // Regression: a negative tapping_term_ms would previously
        // produce `#define TAPPING_TERM_MS -5` and blow up inside
        // QMK. Validate at generation time instead.
        let mut config = BTreeMap::new();
        config.insert("tapping_term_ms".into(), toml::Value::Integer(-5));
        let features = FeaturesToml {
            config,
            ..Default::default()
        };
        let err = emit_config_h(&features).unwrap_err();
        assert!(err.to_string().contains("out of range"));
    }
}
