//! Emit `rules.mk` additions from `features.toml [features]` and the
//! contents of `overlay/`.
//!
//! Walks `overlay/*.c` (Tier 2′ vendored C) and appends each to
//! `SRC +=` so the QMK build picks them up.
//!
//! Tier 2 Zig support is not implemented in v0.1. When we add it, the
//! design will be: pre-compile each `overlay/*.zig` into a `.o` via
//! `zig cc` in the docker backend, then emit a corresponding
//! `EXTRAOBJS += path/to/overlay.o` line here. Until then the Zig path
//! is documented in ARCHITECTURE.md as future work and deliberately
//! not wired up — the process-record-user-collision lint still scans
//! `.zig` files so authored Zig code surfaces in static analysis.

use std::fmt::Write;
use std::path::Path;

use anyhow::{Context, Result};
use walkdir::WalkDir;

use crate::schema::features::FeaturesToml;

/// The set of QMK rules.mk flags that `oryx-bench watch` depends on.
///
/// # Single source of truth
///
/// These three flags are the contract between codegen and `watch`.
/// `watch` reads the live layer state over QMK raw HID using the Oryx
/// module's protocol (usage page 0xFF60, usage 0x61, 32-byte reports).
/// The firmware only answers that protocol when all three are enabled:
///
/// - `RAW_ENABLE = yes` — the raw HID endpoint itself.
/// - `COMMUNITY_MODULES += oryx` — the Oryx HID message handler (the
///   one that responds to our `GetStatus`/`SetLayer` messages).
/// - `RGB_MATRIX_ENABLE = yes` — the Oryx module's `keymap_callbacks.c`
///   references the RGB matrix layer API; without it the module fails
///   to link.
///
/// Every firmware built by `oryx-bench build` must carry these. They
/// live here and only here — `src/watch/hid.rs` references the same
/// names in its handshake error message and in the verification log
/// entry §V3, but the list itself is owned by codegen because codegen
/// is the enforcement point. Lint would be evadable (a user can skip
/// lint); the generator cannot be skipped on the `build` path.
///
/// If you add a new flag here, mirror the change in the handshake
/// error message in `src/watch/hid.rs` (search for `RAW_ENABLE`).
pub const WATCH_REQUIRED_RULES_MK: &[(&str, &str)] = &[
    ("RAW_ENABLE", "yes"),
    ("RGB_MATRIX_ENABLE", "yes"),
    ("COMMUNITY_MODULES", "+= oryx"),
];

/// Emit the additive `rules.mk` body.
pub fn emit_rules_mk(
    features: &FeaturesToml,
    overlay_dir: Option<&Path>,
    has_tap_dances: bool,
) -> Result<String> {
    // Refuse to generate firmware that `oryx-bench watch` cannot talk
    // to. `rgb_matrix = false` in `[features]` would override the
    // `RGB_MATRIX_ENABLE = yes` we inject below and silently break
    // `watch`. `RAW_ENABLE` and `COMMUNITY_MODULES` are not reachable
    // from `[features]` at all — the schema has no toggle for them —
    // so the hard rejection path is only needed for `rgb_matrix`. We
    // error (rather than warn-and-override) because the user has told
    // us "disable the RGB matrix" and producing firmware that quietly
    // enables it anyway would be a workaround masquerading as a fix.
    if let Some(false) = features.features.get("rgb_matrix") {
        anyhow::bail!(
            "features.toml sets `rgb_matrix = false`, but \
             `oryx-bench watch` requires RGB_MATRIX_ENABLE = yes to \
             read live layer state from the keyboard. Remove the \
             toggle (or set it to true) — RGB_MATRIX is a hard \
             dependency of the Oryx HID handler, not an optional \
             feature."
        );
    }

    let mut out = String::new();
    out.push_str("# SPDX-License-Identifier: MIT\n");
    out.push_str("# Generated by oryx-bench. Do not edit by hand.\n\n");

    // Injected unconditionally so `oryx-bench watch` works against
    // every firmware we build. See WATCH_REQUIRED_RULES_MK for the
    // rationale. Emitting these early means any later `?=` style
    // assignment from upstream rules.mk snippets is a no-op and our
    // values win.
    out.push_str("# Injected by `oryx-bench build` so `oryx-bench watch` can read the\n");
    out.push_str("# keyboard's live layer state over raw HID. Do not remove — watch\n");
    out.push_str("# will error out at handshake time if any of these are missing.\n");
    for (name, value) in WATCH_REQUIRED_RULES_MK {
        // `COMMUNITY_MODULES` uses `+=` (append to any upstream list);
        // the plain `yes`/`no` flags use `=`. The value string carries
        // the operator so this stays data-driven.
        if value.starts_with("+=") || value.starts_with('=') {
            let _ = writeln!(out, "{name} {value}");
        } else {
            let _ = writeln!(out, "{name} = {value}");
        }
    }
    out.push('\n');

    // Translate [features] toggles into QMK feature flags.
    out.push_str("# Feature flags from overlay/features.toml [features]\n");
    let mut keys: Vec<&String> = features.features.keys().collect();
    keys.sort();
    for key in keys {
        let yes = features.features[key];
        let flag_name = match key.as_str() {
            "key_overrides" => "KEY_OVERRIDE_ENABLE",
            "combos" => "COMBO_ENABLE",
            "caps_word" => "CAPS_WORD_ENABLE",
            "mouse_keys" => "MOUSEKEY_ENABLE",
            "tap_dance" => "TAP_DANCE_ENABLE",
            // `rgb_matrix` is enforced above via WATCH_REQUIRED_RULES_MK.
            // Skipping it here avoids a duplicate `RGB_MATRIX_ENABLE =
            // yes` line when the user sets `rgb_matrix = true`, and the
            // `rgb_matrix = false` case is already rejected at the top
            // of this function.
            "rgb_matrix" => continue,
            other => {
                // Fallback: uppercase + _ENABLE
                let _ = writeln!(
                    out,
                    "{}_ENABLE = {}",
                    other.to_uppercase(),
                    if yes { "yes" } else { "no" }
                );
                continue;
            }
        };
        let _ = writeln!(out, "{flag_name} = {}", if yes { "yes" } else { "no" });
    }
    out.push('\n');

    // Auto-enable tap dance when the layout uses double_tap keys,
    // regardless of whether the user declared it in [features].
    if has_tap_dances && !features.features.contains_key("tap_dance") {
        out.push_str("# Auto-enabled: layout uses tap-dance keys\n");
        out.push_str("TAP_DANCE_ENABLE = yes\n\n");
    }

    // Disable the DFU suffix. The Voyager's upstream rules.mk stamps
    // vendor/product IDs into the .bin via DFU_SUFFIX_ARGS; `zapp`
    // validates the target device at the USB protocol level, not from
    // file metadata, so the suffix is dead weight in our pipeline.
    // Dropping it also removes a QMK build step that shells out to
    // `dfu-suffix` — one fewer host-side tool the Docker image has
    // to ship.
    out.push_str("# Disable DFU suffix — unused by zapp; removes a host-side build dep\n");
    out.push_str("DFU_SUFFIX_ARGS =\n\n");

    // Always-on additions: the generated _features.c.
    out.push_str("SRC += _features.c\n");

    // Walk overlay/ for .c files. Walkdir errors propagate so we
    // don't silently miss a file the user is expecting to compile.
    if let Some(dir) = overlay_dir {
        if dir.exists() {
            let mut c_files: Vec<String> = Vec::new();
            for entry in WalkDir::new(dir) {
                let entry = entry
                    .with_context(|| format!("walking overlay directory {}", dir.display()))?;
                if let Some(ext) = entry.path().extension().and_then(|s| s.to_str()) {
                    if ext == "c" {
                        let rel = entry.path().strip_prefix(dir).with_context(|| {
                            format!("stripping overlay prefix from {}", entry.path().display())
                        })?;
                        c_files.push(rel.display().to_string());
                    }
                }
            }
            c_files.sort();
            if !c_files.is_empty() {
                out.push_str("\n# Tier 2′ vendored C files (overlay/*.c)\n");
                for f in c_files {
                    let _ = writeln!(out, "SRC += {f}");
                }
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use tempfile::TempDir;

    #[test]
    fn emit_rules_mk_translates_feature_flags() {
        let mut feats = BTreeMap::new();
        feats.insert("key_overrides".to_string(), true);
        feats.insert("combos".to_string(), false);
        feats.insert("caps_word".to_string(), true);
        let features = FeaturesToml {
            features: feats,
            ..Default::default()
        };
        let out = emit_rules_mk(&features, None, false).unwrap();
        assert!(out.contains("KEY_OVERRIDE_ENABLE = yes"));
        assert!(out.contains("COMBO_ENABLE = no"));
        assert!(out.contains("CAPS_WORD_ENABLE = yes"));
    }

    #[test]
    fn emit_rules_mk_walks_overlay_for_c_files() {
        let td = TempDir::new().unwrap();
        std::fs::write(td.path().join("foo.c"), "// pasted upstream").unwrap();
        std::fs::write(td.path().join("bar.c"), "// pasted upstream").unwrap();
        std::fs::write(td.path().join("notes.md"), "# ignored").unwrap();
        let out = emit_rules_mk(&FeaturesToml::default(), Some(td.path()), false).unwrap();
        assert!(out.contains("SRC += bar.c"));
        assert!(out.contains("SRC += foo.c"));
        assert!(!out.contains("notes.md"));
    }

    #[test]
    fn always_includes_generated_features_c() {
        let out = emit_rules_mk(&FeaturesToml::default(), None, false).unwrap();
        assert!(out.contains("SRC += _features.c"));
    }

    #[test]
    fn emit_rules_mk_auto_enables_tap_dance() {
        let out = emit_rules_mk(&FeaturesToml::default(), None, true).unwrap();
        assert!(out.contains("TAP_DANCE_ENABLE = yes"));
        assert!(out.contains("Auto-enabled"));
    }

    #[test]
    fn emit_rules_mk_no_auto_enable_when_no_tap_dances() {
        let out = emit_rules_mk(&FeaturesToml::default(), None, false).unwrap();
        assert!(!out.contains("TAP_DANCE_ENABLE"));
    }

    /// Every firmware we build must carry the three Oryx HID flags so
    /// that `oryx-bench watch` works out of the box. This is the
    /// contract described by `WATCH_REQUIRED_RULES_MK`.
    #[test]
    fn always_emits_watch_required_rules_mk_flags() {
        let out = emit_rules_mk(&FeaturesToml::default(), None, false).unwrap();
        assert!(
            out.contains("RAW_ENABLE = yes"),
            "missing RAW_ENABLE in:\n{out}"
        );
        assert!(
            out.contains("RGB_MATRIX_ENABLE = yes"),
            "missing RGB_MATRIX_ENABLE in:\n{out}"
        );
        assert!(
            out.contains("COMMUNITY_MODULES += oryx"),
            "missing COMMUNITY_MODULES += oryx in:\n{out}"
        );
        // The rationale comment must ship with the flags so a user
        // inspecting the generated rules.mk understands why they're
        // there and doesn't strip them out.
        assert!(
            out.contains("oryx-bench watch"),
            "missing rationale comment in:\n{out}"
        );
    }

    /// Even when the user declares `rgb_matrix = true` in [features],
    /// we must not emit a duplicate `RGB_MATRIX_ENABLE = yes` line.
    /// The injected block at the top is the single source of truth.
    #[test]
    fn rgb_matrix_true_in_features_does_not_duplicate() {
        let mut feats = BTreeMap::new();
        feats.insert("rgb_matrix".to_string(), true);
        let features = FeaturesToml {
            features: feats,
            ..Default::default()
        };
        let out = emit_rules_mk(&features, None, false).unwrap();
        let occurrences = out.matches("RGB_MATRIX_ENABLE = yes").count();
        assert_eq!(
            occurrences, 1,
            "RGB_MATRIX_ENABLE = yes should appear exactly once, got {occurrences}:\n{out}"
        );
    }

    /// `rgb_matrix = false` is a hard error: it would break `watch`.
    /// We refuse to generate firmware rather than silently overriding
    /// the user's toggle.
    #[test]
    fn rgb_matrix_false_in_features_is_rejected() {
        let mut feats = BTreeMap::new();
        feats.insert("rgb_matrix".to_string(), false);
        let features = FeaturesToml {
            features: feats,
            ..Default::default()
        };
        let err = emit_rules_mk(&features, None, false).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("rgb_matrix") && msg.contains("watch"),
            "error should explain the conflict with watch, got: {msg}"
        );
    }

    /// Order matters: the injected block must appear before the
    /// `[features]`-driven block. Both use `=` assignments, and if the
    /// user-driven block came first any downstream reader scanning
    /// top-to-bottom would find the user's stale value before the
    /// enforced one.
    #[test]
    fn watch_required_block_appears_before_features_block() {
        let mut feats = BTreeMap::new();
        feats.insert("key_overrides".to_string(), true);
        let features = FeaturesToml {
            features: feats,
            ..Default::default()
        };
        let out = emit_rules_mk(&features, None, false).unwrap();
        let raw_pos = out.find("RAW_ENABLE = yes").unwrap();
        let ko_pos = out.find("KEY_OVERRIDE_ENABLE = yes").unwrap();
        assert!(
            raw_pos < ko_pos,
            "RAW_ENABLE should be emitted before KEY_OVERRIDE_ENABLE"
        );
    }
}
